# Generated by Django 5.1.4 on 2025-01-05 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
